NAME_PROJECT=rand

DIRECTORY_INCLUDE=include
DIRECTORY_OBJECTS=objects
DIRECTORY_OBJECTS_EXECUTABLE=$(DIRECTORY_OBJECTS)/executable
DIRECTORY_OUTPUT_EXECUTABLE=executable
DIRECTORY_OUTPUT_LIBRARY=library
DIRECTORY_SOURCES=sources
DIRECTORY_SOURCES_EXECUTABLE=$(DIRECTORY_SOURCES)/executable

FILE_OUTPUT_EXECUTABLE=$(DIRECTORY_OUTPUT_EXECUTABLE)/$(NAME_PROJECT)
FILE_OUTPUT_LIBRARY=$(DIRECTORY_OUTPUT_LIBRARY)/$(NAME_PROJECT).o

FILES_SOURCES_EXECUTABLE=$(wildcard $(DIRECTORY_SOURCES_EXECUTABLE)/*.c)
FILES_SOURCES_LIBRARY=$(wildcard $(DIRECTORY_SOURCES)/*.c)

FILES_OBJECTS_EXECUTABLE=$(patsubst $(DIRECTORY_SOURCES_EXECUTABLE)/%.c, $(DIRECTORY_OBJECTS_EXECUTABLE)/%.o, $(FILES_SOURCES_EXECUTABLE))
FILES_OBJECTS_LIBRARY=$(patsubst $(DIRECTORY_SOURCES)/%.c, $(DIRECTORY_OBJECTS)/%.o, $(FILES_SOURCES_LIBRARY))

SYMBOL_ENTRY_POINT=$(NAME_PROJECT)_executable

CC=gcc
C_FLAGS=-O3 -I$(DIRECTORY_INCLUDE)

LD=ld
L_FLAGS=

all: library executable

executable: $(FILE_OUTPUT_EXECUTABLE)

library: $(FILE_OUTPUT_LIBRARY)

$(FILE_OUTPUT_LIBRARY): directories_library $(FILES_OBJECTS_LIBRARY)
	$(LD) $(L_FLAGS) -r $(FILES_OBJECTS_LIBRARY) -o $@

$(FILE_OUTPUT_EXECUTABLE): directories_executable $(FILES_OBJECTS_LIBRARY) $(FILES_OBJECTS_EXECUTABLE)
	$(CC) $(C_FLAGS) $(FILES_OBJECTS_LIBRARY) $(FILES_OBJECTS_EXECUTABLE) -e $(SYMBOL_ENTRY_POINT) -o $@

directories: directories_executable directories_library

directories_executable: directories_base
	mkdir -p $(DIRECTORY_OBJECTS_EXECUTABLE)
	mkdir -p $(DIRECTORY_OUTPUT_EXECUTABLE)
	mkdir -p $(DIRECTORY_SOURCES_EXECUTABLE)

directories_library: directories_base
	mkdir -p $(DIRECTORY_OUTPUT_LIBRARY)

directories_base: always
	mkdir -p $(DIRECTORY_INCLUDE)
	mkdir -p $(DIRECTORY_OBJECTS)
	mkdir -p $(DIRECTORY_SOURCES)

$(DIRECTORY_OBJECTS)/%.o: $(DIRECTORY_SOURCES)/%.c
	$(CC) $(C_FLAGS) -c $< -o $@

$(DIRECTORY_OBJECTS_EXECUTABLE)/%.o: $(DIRECTORY_SOURCES_EXECUTABLE)/%.c
	$(CC) $(C_FLAGS) -c $< -o $@

clean: clean_library clean_executable

clean_executable: clean_base
	-rm $(FILE_OUTPUT_EXECUTABLE) 2> /dev/null
	-rm $(DIRECTORY_OBJECTS_EXECUTABLE)/*.o 2> /dev/null

clean_library: clean_base
	-rm $(FILE_OUTPUT_LIBRARY) 2> /dev/null

clean_base:
	-rm $(DIRECTORY_OBJECTS)/*.o 2> /dev/null

always:

