name: debug_continuous_integration_build
on:
  push:
    branches: [ "core" ]
  pull_request:
    branches: [ "core" ]
jobs:
  debug_continuous_integration_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: debug_continuous_integration_build_make
      run: mkdir -p include && mkdir -p objects && mkdir -p sources && mkdir -p library && gcc -O3 -Iinclude -c sources/rand_alph.c -o objects/rand_alph.o && gcc -O3 -Iinclude -c sources/rand_dec.c -o objects/rand_dec.o && gcc -O3 -Iinclude -c sources/rand_functions.c -o objects/rand_functions.o && gcc -O3 -Iinclude -c sources/rand_hex.c -o objects/rand_hex.o && gcc -O3 -Iinclude -c sources/rand_numalph.c -o objects/rand_numalph.o && gcc -O3 -Iinclude -c sources/rand_options.c -o objects/rand_options.o && gcc -O3 -Iinclude -c sources/rand_result.c -o objects/rand_result.o && gcc -O3 -Iinclude -c sources/rand_source.c -o objects/rand_source.o && ld  -r  objects/rand_alph.o  objects/rand_dec.o  objects/rand_functions.o  objects/rand_hex.o  objects/rand_numalph.o  objects/rand_options.o  objects/rand_result.o  objects/rand_source.o -o library/rand.o && mkdir -p objects/executable && mkdir -p executable && mkdir -p sources/executable && gcc -O3 -Iinclude -c sources/executable/rand_executable.c -o objects/executable/rand_executable.o && gcc -O3 -Iinclude -c sources/executable/rand_print_usage.c -o objects/executable/rand_print_usage.o && hexdump objects/executable/rand_executable.o

